development:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:4acead9715c5d172df7f7df31ab4c029@soapfish.redistogo.com:11341/" } %>
  channel_prefix: group19project_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:4acead9715c5d172df7f7df31ab4c029@soapfish.redistogo.com:11341/" } %>
  channel_prefix: group19project_production
